# Generated by Django 5.2.15 on 2026-07-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='subtítulo')),
                ('imagem', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True)),
                ('texto_botao', models.CharField(blank=True, max_length=60, verbose_name='texto do botão')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
