# Generated by Django 5.2.15 on 2026-07-01 20:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='SKU')),
                ('marca', models.CharField(default='Metalab', max_length=120)),
                ('descricao_curta', models.CharField(blank=True, max_length=255)),
                ('descricao_completa', models.TextField(blank=True)),
                ('composicao', models.TextField(blank=True)),
                ('modo_uso', models.TextField(blank=True, verbose_name='modo de uso')),
                ('aviso_legal', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=5)),
                ('peso', models.PositiveIntegerField(blank=True, null=True, verbose_name='peso (g)')),
                ('altura', models.PositiveIntegerField(blank=True, null=True, verbose_name='altura (cm)')),
                ('largura', models.PositiveIntegerField(blank=True, null=True, verbose_name='largura (cm)')),
                ('comprimento', models.PositiveIntegerField(blank=True, null=True, verbose_name='comprimento (cm)')),
                ('imagem_principal', models.ImageField(blank=True, upload_to='produtos/')),
                ('imagem_2', models.ImageField(blank=True, upload_to='produtos/')),
                ('imagem_3', models.ImageField(blank=True, upload_to='produtos/')),
                ('imagem_4', models.ImageField(blank=True, upload_to='produtos/')),
                ('ativo', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.categoria')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/galeria/')),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'imagem do produto',
                'verbose_name_plural': 'imagens do produto',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['ativo', 'destaque'], name='produtos_pr_ativo_422406_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['ativo', 'categoria'], name='produtos_pr_ativo_68fd0c_idx'),
        ),
    ]
