# Generated by Django 5.2.15 on 2026-07-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cor_principal',
            field=models.CharField(blank=True, help_text='Hex, ex.: #002659', max_length=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='cor_secundaria',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='meta_descricao',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='produto',
            name='meta_titulo',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
