# Generated by Django 5.2.15 on 2026-07-01 20:40

import django.core.validators
import django.db.models.deletion
import pedidos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('cupons', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=pedidos.models.gerar_codigo_pedido, max_length=20, unique=True, verbose_name='código')),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('CONFIRMADO', 'Confirmado'), ('EM_SEPARACAO', 'Em separação'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='NOVO', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('PIX_MANUAL', 'PIX'), ('CARTAO_MANUAL', 'Cartão'), ('BOLETO_MANUAL', 'Boleto')], max_length=20, verbose_name='método de pagamento')),
                ('status_pagamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('RECUSADO', 'Recusado'), ('ESTORNADO', 'Estornado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('comprador_nome', models.CharField(blank=True, max_length=200)),
                ('comprador_email', models.EmailField(blank=True, max_length=254)),
                ('comprador_telefone', models.CharField(blank=True, max_length=20)),
                ('endereco_entrega', models.TextField(blank=True, verbose_name='endereço de entrega')),
                ('estoque_baixado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='clientes.cliente')),
                ('cupom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='cupons.cupom')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto_snapshot', models.CharField(max_length=200)),
                ('sku_snapshot', models.CharField(max_length=60)),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido', to='produtos.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
            },
        ),
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=300, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'histórico de status',
                'verbose_name_plural': 'históricos de status',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status'], name='pedidos_ped_status_65e537_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status_pagamento'], name='pedidos_ped_status__4f8351_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['comprador_email'], name='pedidos_ped_comprad_1dcbbc_idx'),
        ),
    ]
