# Generated by Django 5.2.15 on 2026-07-02 00:23

import pedidos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='idempotency_token',
            field=models.CharField(default=pedidos.models.gerar_idempotency_token, max_length=64, unique=True),
        ),
    ]
