# Generated by Django 5.2.15 on 2026-07-01 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='código')),
                ('tipo', models.CharField(choices=[('PERCENTUAL', 'Percentual (%)'), ('VALOR_FIXO', 'Valor fixo (R$)'), ('FRETE_GRATIS', 'Frete grátis')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ativo', models.BooleanField(default=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('uso_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('usos_realizados', models.PositiveIntegerField(default=0)),
                ('valor_minimo_pedido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cupom',
                'verbose_name_plural': 'cupons',
                'ordering': ['-criado_em'],
            },
        ),
    ]
